title: Sibaek Lee
position: Graduate Student
affiliation: SKKU
email: lmjlss@g.skku.edu
keywords:

google_scholar: https://scholar.google.com/citations?hl=ko&user=BG206AgAAAAJ
github_link: https://github.com/minjae-lulu
youtube: https://www.youtube.com/@aigsmusic
youtube1: https://www.youtube.com/@genesisbeats8070
linkedin: https://www.linkedin.com/in/sibaek-lee-008b1a2a1/

avatar: ./assets/img/mypic.jpeg
google_analytics: UA-111540567-4
favicon: ./assets/img/mypic.jpeg
favicon_dark: ./assets/img/mypic.jpeg
description: Sibaek Lee's homepage
remote_theme: yaoyao-liu/minimal-light

cv_link: ./assets/cv_pdf/cv.pdf