title: Minjae Lee
position: Graduate Student
affiliation: SKKU
email: lmjlss@skku.edu
keywords:

google_scholar: https://scholar.google.com/citations?hl=ko&user=BG206AgAAAAJ
github_link: https://github.com/minjae-lulu
youtube: https://www.youtube.com/@aigsmusic
youtube1: https://www.youtube.com/@genesisbeats8070
instagram: https://www.instagram.com/codingboy_zenesis/

avatar: ./assets/img/mypic.jpeg
google_analytics: UA-111540567-4
favicon: ./assets/img/mypic.jpeg
favicon_dark: ./assets/img/mypic.jpeg
description: Minjae Lee's homepage
remote_theme: yaoyao-liu/minimal-light
